name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create redirect index.html
        run: |
          mkdir -p dist
          cat > dist/index.html << EOL
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Redirecting to Vercel deployment</title>
              <meta http-equiv="refresh" content="0; URL=https://rigger-connect-marketing-p2eaja28b-tiations-projects.vercel.app">
              <link rel="canonical" href="https://rigger-connect-marketing-p2eaja28b-tiations-projects.vercel.app">
            </head>
            <body>
              <p>Redirecting to <a href="https://rigger-connect-marketing-p2eaja28b-tiations-projects.vercel.app">Vercel deployment</a>...</p>
            </body>
          </html>
          EOL

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
